### ISSUE TITLE
indianajones pinball adventure

### ISSUE THREAD

**Issue by Grover54160** [LegendsUnchained/vpx-standalone-alp4k#118]
wrong link for table goes to b2s.  rom volume near silent.

**Comment by T3chZombie** [comment]
Switched the correct links.  Volume issue? You need a keyboard and have to do the open coin door volume fix. https://vpuniverse.com/vpuwiki/mjr_wiki/audio-sounds/how-to-adjust-the-sound-volume-of-roms-r9/
