### ISSUE TITLE
Link to Rocky & Bullwinkle ROM doesn't work

### ISSUE THREAD

**Issue by WenkAK** [LegendsUnchained/vpx-standalone-alp4k#121]
My first time submitting an issue, not sure if this qualifies or not. If not, I'm sorry.

When I follow the link to the rom, the website VP Forums says there is an error. Not sure if the file is not there or not, but I found another site with the rom if that would be helpful. It is the 3.2 version link

https://www.ipdb.org/machine.cgi?id=23

**Comment by Bla1ze** [comment]
@WenkAK This is an issue with VPForums itself as they currently appear to be having issues with their download section.
