### ISSUE TITLE
Discussion Link

### ISSUE THREAD

**Issue by ferrellsl** [LegendsUnchained/vpx-standalone-alp4k#135]
Would it be possible for the maintainer of the repo to enable the "Discussion" link so that people could ask questions and provide info without have to do that under "Issues".  I know several people who have questions and they don't want to create an "Issue" when all they have is a question or want to provide some input.

**Comment by n-i-x** [comment]
That's not something I'm interested in maintaining here on GitHub. When the software is released discussions will happen on Discord.

**Comment by ferrellsl** [comment]
> That's not something I'm interested in maintaining here on GitHub. When the software is released discussions will happen on Discord.

Is the channel up yet?  If so, can you provide a Discord link or Invitation? Thanks in advance.
