### ISSUE TITLE
Incorrect elf file name in instructions For Twisted Metal.

### ISSUE THREAD

**Issue by Drakey83** [LegendsUnchained/vpx-standalone-alp4k#159]
In the instructions it says "Add your personalized launcher.elf and rename it to vpx-flintstones.elf", it should tell you to rename it to "vpx-twistedmetal.elf"

**Comment by MoxAssault** [comment]
Correction has been submitted.

**Comment by SScorpio00** [comment]
Fix PR has been merged.
