### ISSUE TITLE
vpx-fathom - Need to specify B2S file to use

### ISSUE THREAD

**Issue by Mar3nBu** [LegendsUnchained/vpx-standalone-alp4k#176]
@Kaoticbpr you will need to specify which B2S file to download. I'm assuming Fathom (Bally 1981) 3D Anaglyph Backglass Scoring.directB2S is the valid one?

**Comment by Kaoticbpr** [comment]
10-4

**Comment by Kaoticbpr** [comment]
Added note to the readme of which to download and opened a pull request.
