### ISSUE TITLE
vpx-beetlejuicemovie - Incorrect link to ROM

### ISSUE THREAD

**Issue by Mar3nBu** [LegendsUnchained/vpx-standalone-alp4k#177]
@T3chZombie seems like he link provided in README is pointing to Fire Action Deluxe - ROM - fireactd.zip. README indicates the ROM should be strngsci.zip. Found this link for the ROM: https://www.vpforums.org/index.php?app=downloads&showfile=715

Let me know if I'm wrong or if the link needs to be adjusted. I can adjust the README if you need to.

**Comment by T3chZombie** [comment]
Updated the link on the most recent pull request I submitted. Just need for it to be approved. Thank you for catching that.

**Comment by SScorpio00** [comment]
The fix was merged in.
