### ISSUE TITLE
Please Delete if Not Allowed

### ISSUE THREAD

**Issue by Brian-CK** [LegendsUnchained/vpx-standalone-alp4k#249]
Hey,
Would anybody be interested in a script I wrote that automatically renames files when you add them to the table folder?

1. Add a .vpx file and it's renamed to match the .ini file.
2. Add a .directb2s file and it's renamed to match the .ini file.
3. Add your personalized .elf file and it's renamed to match the .xml file.

I've been doing a lot of downloading lately and the script helps immensely.  Eagerly awaiting for my personal .elf file.  My table folders are lonely.  :^)

Cheers!

**Comment by n-i-x** [comment]
Thanks for the offer. The current method of loading tables during the beta will likely not be the final version everyone uses. This is why PDubs hasn't released any tutorials yet, I've asked him to hold off as I'm tweaking the process all the time. The videos posted by dr_wraith are intended to help beta testers onboard into the beta.

I'm working on a wizard that will pull all the configs from the repo automatically and do all the renaming when you add a table using the wizard. It will also create the launcher, etc. for you.

Unfortunately, this means you'll likely need to adapt your current drive to the new setup as it won't work as-is.
