### ISSUE TITLE
Super Mario Bros. table (Tester: mcap) using Super Mario Bros. Mushroom World Backglass

### ISSUE THREAD

**Issue by lilalien** [LegendsUnchained/vpx-standalone-alp4k#252]
Heya,

So the Super Mario Bros. table is using the Mushroom World Backglass, which has it's own VPX table.

We need to change:

FROM:

B2S: https://vpuniverse.com/files/file/18003-super-mario-brothers-mushroom-world-premier-1992-b2s-with-full-dmd/

TO: 

B2S: https://vpuniverse.com/files/file/18004-super-mario-bros-gottlieb-1992-b2s-with-full-dmd/

Did you want to work on Mushroom World as well?

**Comment by mcap10** [comment]
resolved
