### ISSUE TITLE
Stargate (Gottlieb 1995)  - Bad ROM & Backglass Replacement Request

### ISSUE THREAD

**Issue by lilalien** [LegendsUnchained/vpx-standalone-alp4k#253]
Hey,

So it would appear that Stargate needs a different rom, as the current one causes issues.

Here's a link to the one that should be used (stargat5.zip):
https://pinballnirvana.com/forums/resources/stargat5.6026/

Also, there are a couple of other backglass options available that appear more attractive than the one used currently.

Perhaps test this one?
https://vpuniverse.com/files/file/11644-stargate-gottlieb-1995-fulldmd/

Thank you!

**Comment by MoxAssault** [comment]
This has been fixed, and submitted to the repo.
