### ISSUE TITLE
Six Million Dollar Man - Wrong links for both B2S and ROM (Thanks bruno15477)!

### ISSUE THREAD

**Issue by lilalien** [LegendsUnchained/vpx-standalone-alp4k#274]
Repo for the table is located here:
https://github.com/LegendsUnchained/vpx-standalone-alp4k/tree/main/external/vpx-sixmilliondollarman

Wrong B2S and ROM links, will fix!

**Comment by T3chZombie** [comment]
Readme Updated and corrected.
