### ISSUE TITLE
vpx-godfather - Missing instructions for backglass video

### ISSUE THREAD

**Issue by Mar3nBu** [LegendsUnchained/vpx-standalone-alp4k#292]
@Kaoticbpr you might be missing instructions on what to do with the backless video (and might be useful to include the Movie folder in GitHub - if you have it, remember to add the .gitkeep so that it is kept in the repo even when it is empty)

**Comment by Kaoticbpr** [comment]
dont use the video, its choppy and breaks the table. I'll change the readme for that. ignore the movie files completely

**Comment by Mar3nBu** [comment]
Got it.. I can close this ticket then.
