### ISSUE TITLE
vpx-youngfrankenstein - Clarify b2s file and rom download

### ISSUE THREAD

**Issue by Mar3nBu** [LegendsUnchained/vpx-standalone-alp4k#96]
1. VPX zip download contains 3 additional files (on top of vpx file). Are any of those needed? If so, we need to specify where to place those.
2. b2s link has 3 possible download options. We should specify which file should be downloaded / used 
3. Rom link goes to a huge list of different files with no clear definition on which one should be downloaded. Need to clarify this.

**Comment by MoxAssault** [comment]
README file should be corrected shortly to show corrections.

**Comment by Mar3nBu** [comment]
Issue resolved
